[package]
name = "majorana"
version = "0.1.0"
edition = "2021"
definitions = "The sea of thoughts that swims."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
